name: tests

on:
  push:
    branches:
      - main
    paths:
      - 'CMakeLists.txt'
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches:
      - main
    paths:
      - 'CMakeLists.txt'
      - 'src/**'
      - 'tests/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install build dependencies & modern GCC
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install -y \
            build-essential \
            gcc-14 \
            g++-14 \
            cmake \
            pkg-config \
            libcriterion-dev \
            zlib1g-dev

      - name: Configure CMake
        run: |
          cmake -B build \
            -DCMAKE_CXX_COMPILER=g++-14 \
            -DCMAKE_C_COMPILER=gcc-14 \
            -DCMAKE_BUILD_TYPE=Debug \
            -DBUILD_TESTING=ON \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build project and tests
        run: cmake --build build --parallel

      - name: Run tests with CTest
        run: ctest --test-dir build --output-on-failure --verbose
